version: 1

limits:
  max_lines_changed: 500
  max_files_changed: 20

ignore:
  - "*.lock"
  - "*.json"
  - "*.md"
  - "package-lock.json"
  - "pnpm-lock.yaml"
  - "uv.lock"

linting:
  enabled: true
  tool: ruff
  fail_on_error: true
  fail_threshold: 10

security:
  enabled: true
  tool: bandit
  fail_on_severity: high
  max_findings: 5

coverage:
  enabled: true
  min_coverage: 80
  fail_on_decrease: true
  report_path: coverage.xml

dependencies:
  enabled: true
  block_vulnerable: true
  block_deprecated: false
  allowed_licenses:
    - MIT
    - Apache-2.0
    - BSD-3-Clause

escalation:
  enabled: false
  webhook_url: ${ESCALATION_WEBHOOK_URL}
  trigger_below_confidence: 0.5
  slack_format: true

budget:
  enabled: false
  monthly_limit_usd: 500
  alert_at: [0.8, 1.0]
  pause_on_exceed: false
  webhook_url: ${BUDGET_ALERT_WEBHOOK_URL}

llm:
  provider: anthropic
  default_model: claude-sonnet-4-20250514
  simple_model: claude-haiku-4-5-20251001
  simple_threshold_lines: 50
  max_tokens: 4096

confidence:
  high: 0.8
  low: 0.5

review_focus:
  - logic_errors
  - security_issues
  - missing_tests
  - code_patterns
  - naming_conventions
